import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/carousel";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Carousel />
      </main>
    </div>
  );
};

export default Home;
